apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counting-library
  description: Library for managing counters
  tags:
    - kotlin
spec:
  type: service
  lifecycle: experimental
  owner: group:guests
  system: counter-app
  subcomponentOf: counter-service